import React from 'react';

const DiffViewer = () => {
  return (
    <div className="border rounded-md p-4 bg-gray-50">
      <h3 className="font-bold mb-2">Changes</h3>
      <pre>
        <code>
{`
- const Home: NextPage = () => {
+ const Home: NextPage = () => {
-   return (
-     <div>
-       <Head>
-         <title>Next.js Project</title>
-         <meta name="description" content="Generated by create next app" />
-         <link rel="icon" href="/favicon.ico" />
-       </Head>
-
-       <main>
-         <h1>
-           Welcome to <a href="https://nextjs.org">Next.js!</a>
-         </h1>
-       </main>
-     </div>
-   );
- };
+   return <Dashboard />;
+ };
`}
        </code>
      </pre>
    </div>
  );
};

export default DiffViewer;
