import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import PreviewBanner from '../components/PreviewBanner';

type Props = {
  preview: boolean;
};

const Home: NextPage<Props> = ({ preview }) => {
  const previewUrl =
    typeof window !== 'undefined' ? window.location.href : '';

  return (
    <div>
      <Head>
        <title>Next.js Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {preview && <PreviewBanner previewUrl={previewUrl} />}

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {preview && (
          <a href="/api/exit-preview">
            <button>Exit Preview Mode</button>
          </a>
        )}
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ preview = false }) => {
  return {
    props: { preview },
  };
};

export default Home;
