import type { NextPage } from 'next';
import Head from 'next/head';
import TaskList from '../components/TaskList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next.js Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-2xl font-bold mb-4">Local Development Dashboard</h1>
        <TaskList />
      </main>
    </div>
  );
};

export default Home;
